### ISSUE TITLE
Add Mixpanel tracking events

### ISSUE THREAD

**Issue by Safiyya** [Safiyya/circlemapping#140]
- [x] Page views
- [x] Sign up
- [x] Activate
- [x] Login
- [x] Create a team
- [x] Create a map
- [x] Change text size
- [x] Look for help
- [x] Explore initiative view
- [x] Explore team view
