### ISSUE TITLE
Tracking free trials

### ISSUE THREAD

**Issue by Safiyya** [Safiyya/circlemapping#298]
- [ ] Setup a CRM custom field for `TRIAL_PERIOD`
- [ ]  At signup, record `SIGNUP_DATE=now()` and `TRIAL_PERIOD=14` **Webhook Maptio -> CRM**
- [ ]  At login, calculate if trial has expired based on `SIGNUP_DATE` and `TRIAL_PERIOD`
    - [ ] If trial expired, 
        - [ ] redirect to `/payment` page with link to payment page (Chargebee or Outseta) or option  trial period (by email)
        - [ ]  Set team account as `blocked`
    - [ ] If trial not expired, show in `header` a message `Free trial : x days remaining` (admin  only) 
- [ ] To extend a trial, `TRIAL_PERIOD` is changed manually
