### ISSUE TITLE
Changes to new customer onboarding checklist

### ISSUE THREAD

**Issue by tomnixon** [Safiyya/circlemapping#332]
- [x] Remove the space inbetween "get started" and the colon
- [x] Change 'Set up your profile' to 'Set up your user profile'
- [x] The word 'profile' is a link but it's exactly the same as non-link text. Should be different colour and with underline.
- [x] Change 'a organization' to 'an organization' 
- [x] Change 'teammates' to 'people' (Assuming that's what we agreed in #328)
- [x] For the sake of simplicity I think remove "(recommended)" from those two items
- [x] Change 'add a circle' to 'Add some circles' to your map.
