### ISSUE TITLE
Roll out new map to main app

### ISSUE THREAD

**Issue by rgoj** [Safiyya/circlemapping#542]
We want to use the new map UX (https://maptio-preview.web.app/) within the current app.
 
Here is a current (Tuesday 6 July) list of remaining tasks within this issue, grouped by priority (for now reflecting only my take on this):

#### Tasks we need to complete before even launching a preview:
* [x] Deploy current version to staging
* [x] Fix popover broken after upgrading Angular
* [x] Disable the filtering button
* [x] Disable all other buttons not yet implemented and to re-enable them one by one as they're implemented

I'm marking the two tasks above as finished because they are "working as intended" or at least as they work in other parts of the app where they're disabled, but there's a pre-existing bug here: #575 

Similarly marking the popover issue as done for now as it works in production builds, but raised an issue for the problem as it's likely to come back: #576 

#### Tasks we should finish, but could launch a preview without them
* [x] Hide the filter (all disabled buttons) button completely (opacity: 0; pointer-events: none)
* [x] Make search work on the new map
* [x] Switch out the screenshot :)

### Task we agreed - on Tuesday 13 July - we'd try to do before launching
* [x] Testing, testing, testing
* [x] BUG: Fix pinch to zoom on the d3 maps (this works in production)
* [x] Make the expanded view the default for now
* [x] The selected and opened node should have the same opacity it had before opening; it should also retain the drop shadow, but the border can now disappear
* [x] Make avatars clickable on the map
* [x] Make tags non-clickable for now (change pointer)
* [x] On hover over a circle, show it's full name - this is to help with maps where there are very small circles
* [x] Use a different icon for the gradual reveal map
* [x] Consider removing the text from the toolbar if there isn't enough height or width
* [ ] When editing using the tree view, we should be selecting (and opening, e.g. when adding children) circles just as if they had been clicked
* [x] Finish implementing zooming and panning
  * [x] Wire up zoom in and out buttons
  * [x] Wire up zoom fit button
  * [x] Zoom on scroll events
  * [x] Pinch to zoom
  * [x] Implement panning
* [ ] Add a per-team setting to choose which circles view should be the default, make the new view the default for new users, with old users defaulting to the old view

#### Other tasks, probably less important
* [ ] Filter on the new map with next/prev buttons (1-2 days)
* [ ] Implement the context menu for circles
* [ ] When switching to the expanded view from the new map ux view, the selected node is not zoomed in, whereas it is when first opening the map! (that is also true when switching back from the network view, this appears to be a long-standing inconsistency)
* [ ] Adjust margins so that the toolbar doesn't obscure the edges of the map if there isn't enough horizontal space
