### ISSUE TITLE
Become GDPR-compliant

### ISSUE THREAD

**Issue by rgoj** [Safiyya/circlemapping#650]
It'd be great to do an audit of all the services we're using to see whether we are / what we need to do to become GDPR-compliant.

Our privacy policy is generic and needs to be updated, so it'd be good to do that as part of this work.

We made a small start in #649  prompted by this [customer query](https://app.intercom.com/a/apps/q3x5lnhp/inbox/inbox/all/conversations/106323200001909).

### TODOs
Here's an incomplete list of what'd be great to do as part of this, intended as a living list with things added to it as we think of them.

#### Necessary for compliance
* [ ] Check each service we're using to ensure their GDPR compliance (and whether we need to make any adjustments in settings, privacy policy clauses, etc.):
  * [ ] Intercom
  * [ ] Auth0
  * [ ] MongoDB Atlas
  * [ ] Heroku (logs could potentially contain user data)
  * [x] LogRocket (removed recently)
* [ ] Audit the code for any other services we might be using
* [ ] Audit the cookies set in production for anything we might miss in the task above
* [ ] Update the policy with all of the findings / adjustments from the work above
* [ ] Create consent functionality for any non-necessary services / as required
* [ ] Check what's necessary to make the public-facing website compliant too

#### Related
* [ ] In #649 , we just hacked away at the code to ensure data is no longer sent to Fullstory and Mixpanel, it'd be great to remove all of the surrounding code (e.g. in the analytics service)
